resources:
- azure-private-endpoint-operator.yaml
- azure-workload-identity-webhook.yaml
- cluster-api-provider-azure.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-azure.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- gateway-api-bundle.yaml
- keda.yaml
- konfiguration.v2.yaml
- oauth2-proxy.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
