resources:
- azure-private-endpoint-operator.yaml
- azure-workload-identity-webhook.yaml
- cluster-api-provider-azure.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-azure.yaml
- event-exporter-app.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- trivy-operator.yaml
