resources:
- app-admission-controller.yaml
- app-exporter.yaml
- app-operator.yaml
- athena.yaml
- azure-private-endpoint-operator.yaml
- azure-workload-identity-webhook.yaml
- cloudnative-pg.yaml
- cluster-api-events.yaml
- cluster-api-provider-azure.yaml
- cluster-api.yaml
- cluster-apps-operator.yaml
- cluster-cleaner.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-azure.yaml
- encryption-provider-operator.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- gateway-api-bundle.yaml
- grafana.yaml
- happa.yaml
- ingress-nginx.yaml
- keda.yaml
- konfiguration.v2.yaml
- kube-downscaler.yaml
- kyverno-policies-connectivity.yaml
- kyverno-policies-dx.yaml
- kyverno-policies-observability.yaml
- kyverno-policies-ux.yaml
- loki.yaml
- mimir.yaml
- oauth2-proxy.yaml
- object-storage-operator.yaml
- observability-operator.yaml
- observability-platform-api.yaml
- organization-operator.yaml
- plugin-barman-cloud.yaml
- prometheus-remotewrite.yaml
- prometheus-rules.yaml
- rbac-operator.yaml
- silence-operator.yaml
- sloth-rules.yaml
- sloth.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
- upgrade-schedule-operator.yaml
