api_version: generators.giantswarm.io/v1
app_catalog: control-plane-catalog
app_destination_namespace: kube-system
app_name: ingress-nginx
app_version: 3.4.2
kind: Konfigure
metadata:
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: /plugins/konfigure
  name: ingress-nginx
name: ingress-nginx
